services:
  observatibilityfirststeps:
    image: jaegertracing/all-in-one:1.61.0
    build:
      context: .
      dockerfile: ObservatibilityFirstSteps/Dockerfile
  observatibilityfirststeps-zipkin:
    image: openzipkin/zipkin:latest
    build:
     context: .
     dockerfile: ObservatibilityFirstSteps/Dockerfile-zipkin