services:
  observatibilityfirststeps:
    image: jaegertracing/all-in-one:1.72.0
    build:
      context: .
      dockerfile: ObservatibilityFirstSteps/Dockerfile
  # observatibilityfirststeps-zipkin:
  #   image: openzipkin/zipkin:latest
  #   build:
  #    context: .
  #    dockerfile: ObservatibilityFirstSteps/Dockerfile-zipkin
  redis:
    image: redis:alpine3.22
  rabbitmq:
    image: rabbitmq:4.2-rc-management-alpine
  elasticsearch:
    image: elasticsearch:9.1.2
  kibana:
    image: kibana:9.1.2